import { randomUUID } from 'node:crypto';

import type { AgentRegistry } from '@anx/agents';
import {
  buildEvent,
  type AgentCompletedEvent,
  type AgentFailedEvent,
  type AgentStartedEvent,
  type ChatCompletionChunk,
  type ChatCompletionRequest,
  type ChatCompletionResponse,
  type EventBusPort,
  ProviderResponseError,
} from '@anx/core';
import { retry, sleep } from '@anx/shared';

/**
 * ───────────────────────────────────────────────────────────────────────────
 * Agent Runtime — executes tasks against registered agents.
 *
 * Responsibilities:
 *   - Start / stop agent sessions (with isolation)
 *   - Send tasks (chat completions) to an agent
 *   - Stream events (chunks) back to the caller
 *   - Retry on transient failures
 *   - Enforce timeouts
 *   - Emit agent.started / agent.completed / agent.failed events
 *   - Track token usage + cost per agent
 *
 * The runtime itself does NOT call provider APIs directly — it delegates
 * that to the gateway's ChatCompletionUseCase via the `Executor` port.
 * This keeps the runtime testable without provider credentials.
 * ───────────────────────────────────────────────────────────────────────────
 */

export interface TaskRequest {
  readonly id: string;          // pre-generated by caller
  readonly agentId: string;
  readonly model: string;
  readonly messages: ChatCompletionRequest['messages'];
  readonly systemPrompt?: string;
  readonly temperature?: number;
  readonly maxTokens?: number;
  readonly tools?: ChatCompletionRequest['tools'];
  readonly toolChoice?: ChatCompletionRequest['toolChoice'];
  readonly streaming?: boolean;
  readonly timeoutMs?: number;
  readonly maxRetries?: number;
  readonly metadata?: Record<string, unknown>;
}

export interface TaskResult {
  readonly taskId: string;
  readonly agentId: string;
  readonly sessionId: string;
  readonly success: boolean;
  readonly response?: ChatCompletionResponse;
  readonly error?: { message: string; code: string; attempt: number };
  readonly attempts: number;
  readonly durationMs: number;
  readonly tokensUsed: number;
  readonly costUsd: number;
}

/**
 * Executor port — the runtime calls this to actually hit a provider.
 * In production, this is wired to the gateway's ChatCompletionUseCase.
 * In tests, this is a fake.
 */
export interface TaskExecutor {
  execute(
    request: ChatCompletionRequest,
    sink?: ChunkSink,
    signal?: AbortSignal,
  ): Promise<ChatCompletionResponse>;
}

export interface ChunkSink {
  write(chunk: ChatCompletionChunk): Promise<void>;
  error(error: Error): Promise<void>;
  end(): Promise<void>;
}

export interface AgentSession {
  readonly id: string;
  readonly agentId: string;
  readonly startedAt: Date;
  endedAt?: Date;
  taskCount: number;
  tokensUsed: number;
  costUsd: number;
}

/**
 * The runtime.
 */
export class AgentRuntime {
  private readonly sessions = new Map<string, AgentSessionImpl>();

  constructor(
    private readonly agents: AgentRegistry,
    private readonly executor: TaskExecutor,
    private readonly events: EventBusPort,
    private readonly defaults: { timeoutMs?: number; maxRetries?: number } = {},
  ) {}

  /**
   * Open a new session for an agent. Sessions isolate context (memory,
   * tool state) per conversation.
   */
  openSession(agentId: string): AgentSession {
    const agent = this.agents.get(agentId);
    if (!agent) throw new Error(`Unknown agent: ${agentId}`);
    const session: AgentSessionImpl = {
      id: randomUUID(),
      agentId,
      startedAt: new Date(),
      taskCount: 0,
      tokensUsed: 0,
      costUsd: 0,
    };
    this.sessions.set(session.id, session);
    return session;
  }

  closeSession(sessionId: string): void {
    const session = this.sessions.get(sessionId);
    if (session) session.endedAt = new Date();
    this.sessions.delete(sessionId);
  }

  getSession(sessionId: string): AgentSession | undefined {
    return this.sessions.get(sessionId);
  }

  listSessions(): readonly AgentSession[] {
    return Array.from(this.sessions.values());
  }

  /**
   * Execute a task. The runtime:
   *   1. Resolves the agent from the registry
   *   2. Marks the agent as busy
   *   3. Builds a ChatCompletionRequest from the TaskRequest
   *   4. Calls the executor (with retry + timeout)
   *   5. Streams chunks to the sink (if streaming)
   *   6. Records token usage + cost
   *   7. Emits agent.started / agent.completed / agent.failed
   *   8. Marks the agent as online again
   */
  async executeTask(task: TaskRequest, sink?: ChunkSink): Promise<TaskResult> {
    const agent = this.agents.get(task.agentId);
    if (!agent) {
      return {
        taskId: task.id,
        agentId: task.agentId,
        sessionId: '',
        success: false,
        error: { message: `Unknown agent: ${task.agentId}`, code: 'AGENT_NOT_FOUND', attempt: 0 },
        attempts: 0,
        durationMs: 0,
        tokensUsed: 0,
        costUsd: 0,
      };
    }

    if (agent.status === 'offline') {
      return {
        taskId: task.id,
        agentId: task.agentId,
        sessionId: '',
        success: false,
        error: { message: `Agent ${task.agentId} is offline`, code: 'AGENT_OFFLINE', attempt: 0 },
        attempts: 0,
        durationMs: 0,
        tokensUsed: 0,
        costUsd: 0,
      };
    }

    const session = this.sessions.get(task.metadata?.['sessionId'] as string) ?? this.openSession(task.agentId);
    const correlationId = task.id;
    const startedAt = Date.now();
    const timeoutMs = task.timeoutMs ?? this.defaults.timeoutMs ?? 120_000;
    const maxRetries = task.maxRetries ?? this.defaults.maxRetries ?? 2;

    await this.agents.incrementTaskCount(task.agentId);

    await this.events.publish(
      buildEvent<AgentStartedEvent>(
        'agent.started',
        { agentId: task.agentId, taskId: task.id, sessionId: session.id },
        correlationId,
      ),
    );

    const request = this.buildRequest(task);
    const controller = new AbortController();
    const timeout = AbortSignal.timeout(timeoutMs);
    const onAbort = () => controller.abort();
    timeout.addEventListener('abort', onAbort, { once: true });

    let attempt = 0;
    let lastError: Error | undefined;
    let response: ChatCompletionResponse | undefined;

    try {
      const result = await retry(
        async () => {
          attempt++;
          return this.executor.execute(request, sink, controller.signal);
        },
        {
          retries: maxRetries,
          initialDelayMs: 500,
          maxDelayMs: 5_000,
          factor: 2,
          shouldRetry: (err) => this.isRetryable(err),
        },
      );
      response = result;
    } catch (err) {
      lastError = err as Error;
    } finally {
      timeout.removeEventListener('abort', onAbort);
    }

    const durationMs = Date.now() - startedAt;
    await this.agents.decrementTaskCount(task.agentId);

    // Update session stats
    session.taskCount++;
    if (response?.usage) {
      session.tokensUsed += response.usage.totalTokens;
    }
    if (response?.costUsd) {
      session.costUsd += response.costUsd * (agent.costMultiplier ?? 1.0);
    }

    if (response) {
      const tokensUsed = response.usage?.totalTokens ?? 0;
      const costUsd = (response.costUsd ?? 0) * (agent.costMultiplier ?? 1.0);

      await this.events.publish(
        buildEvent<AgentCompletedEvent>(
          'agent.completed',
          {
            agentId: task.agentId,
            taskId: task.id,
            sessionId: session.id,
            durationMs,
            tokensUsed,
            costUsd,
            success: true,
          },
          correlationId,
        ),
      );

      return {
        taskId: task.id,
        agentId: task.agentId,
        sessionId: session.id,
        success: true,
        response,
        attempts: attempt,
        durationMs,
        tokensUsed,
        costUsd,
      };
    }

    // Failure path
    const error = lastError ?? new Error('unknown error');
    const code = (error as { code?: string }).code ?? 'UNKNOWN';

    await this.events.publish(
      buildEvent<AgentFailedEvent>(
        'agent.failed',
        {
          agentId: task.agentId,
          taskId: task.id,
          sessionId: session.id,
          error: error.message,
          code,
          attempt,
        },
        correlationId,
      ),
    );

    return {
      taskId: task.id,
      agentId: task.agentId,
      sessionId: session.id,
      success: false,
      error: { message: error.message, code, attempt },
      attempts: attempt,
      durationMs,
      tokensUsed: 0,
      costUsd: 0,
    };
  }

  /**
   * Execute multiple tasks in parallel. Respects each agent's concurrency
   * limit (enforced by the registry's task count).
   */
  async executeParallel(tasks: readonly TaskRequest[]): Promise<readonly TaskResult[]> {
    return Promise.all(tasks.map((t) => this.executeTask(t)));
  }

  // ─────────────────────────────────────────────────────────────────────────

  private buildRequest(task: TaskRequest): ChatCompletionRequest {
    const messages = task.systemPrompt
      ? [{ role: 'system' as const, content: task.systemPrompt }, ...task.messages]
      : task.messages;
    return {
      model: task.model,
      messages,
      temperature: task.temperature,
      maxTokens: task.maxTokens,
      tools: task.tools,
      toolChoice: task.toolChoice,
      stream: task.streaming,
      user: task.agentId,
      metadata: { taskId: task.id, agentId: task.agentId, ...task.metadata },
    };
  }

  private isRetryable(error: Error): boolean {
    if (error instanceof ProviderResponseError) {
      return error.status >= 500 || error.status === 408 || error.status === 429;
    }
    const code = (error as { code?: string }).code;
    return (
      code === 'ECONNRESET' ||
      code === 'ETIMEDOUT' ||
      code === 'ECONNREFUSED' ||
      code === 'EAI_AGAIN' ||
      code === 'UND_ERR_CONNECT_TIMEOUT' ||
      error.name === 'AbortError'
    );
  }
}

interface AgentSessionImpl extends AgentSession {
  endedAt?: Date;
}

/**
 * In-memory TaskExecutor for tests and local-only deployments.
 */
export class InMemoryTaskExecutor implements TaskExecutor {
  constructor(
    private readonly handler: (request: ChatCompletionRequest) => Promise<ChatCompletionResponse>,
  ) {}

  async execute(
    request: ChatCompletionRequest,
    _sink?: ChunkSink,
    _signal?: AbortSignal,
  ): Promise<ChatCompletionResponse> {
    return this.handler(request);
  }
}

/**
 * Generate a task id.
 */
export function generateTaskId(): string {
  return `task-${randomUUID()}`;
}

export { sleep };
